name: Build

on: [push]

jobs:
  build:


    strategy:
      matrix:
        target:
        - i686-unknown-linux-gnu
        - x86_64-unknown-linux-gnu
        - aarch64-unknown-linux-gnu
        - arm-unknown-linux-gnueabihf
        - mips-unknown-linux-gnu
        - mips64-unknown-linux-gnuabi64
        - powerpc-unknown-linux-gnu
        - powerpc64-unknown-linux-gnu
        version:
        - 1.34.0
        - stable
        - beta
        - nightly
        features:
        - --all-features
        - --no-default-features
        include:
        - target: i686-unknown-linux-gnu
          test: true
        - target: x86_64-unknown-linux-gnu
          test: true

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install toolchain
      run: |
        rustup install --profile minimal ${{ matrix.version }}
        rustup default ${{ matrix.version }}
        rustup target add ${{ matrix.target }}
    - name: Build without test
      if: ${{ !matrix.test }}
      run: cargo build --verbose --target ${{ matrix.target }} ${{ matrix.features }}
    - name: Run tests
      if: ${{ matrix.test }}
      run: cargo test --verbose --target ${{ matrix.target }} ${{ matrix.features }}
